### ISSUE TITLE
Some resources are missing

### ISSUE THREAD

**Issue by ggerbaud** [gocaine/go-dart#33]
release v1.0.0-beta32
![image](https://cloud.githubusercontent.com/assets/616110/17834210/b65bc7ec-6735-11e6-852c-ecccf4d7a1ed.png)

**Comment by mathieu-pousse** [comment]
check with a browser, i mean, a real one, not internet explorer !

**Comment by mathieu-pousse** [comment]
does it display ? https://design.google.com/icons/#ic_accessibility

**Comment by ggerbaud** [comment]
Ok, not a go-dart bug
