### ISSUE TITLE
oss law

### ISSUE THREAD

**Issue by mathieu-pousse** [gocaine/go-dart#48]
add licence and credits for images

**Comment by ggerbaud** [comment]
You mean ?
> add licence *FOR THE PROJECT* and credits for images

**Comment by mathieu-pousse** [comment]
Ja

**Comment by ggerbaud** [comment]
Any idea for the licence ?

**Comment by erwannT** [comment]
We should verify if there are no restrictives licence with our libraries

**Comment by mathieu-pousse** [comment]
embd  - MIT
viper - MIT
cobra - MIT
gin - MIT

**Comment by ggerbaud** [comment]
esc - MIT

**Comment by ggerbaud** [comment]
hum : https://github.com/google/uuid/blob/master/LICENSE

**Comment by mathieu-pousse** [comment]
this is the google one: same as for golang https://golang.org/LICENSE

**Comment by mathieu-pousse** [comment]
Go for MIT then
